//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class LibraryClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "http://localhost:5114";
    }

    getAuthors(): Promise<AuthorDto[]> {
        let url_ = this.baseUrl + "/api/library/authors";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAuthors(_response);
        });
    }

    protected processGetAuthors(response: Response): Promise<AuthorDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(AuthorDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AuthorDto[]>(null as any);
    }

    createAuthor(dto: CreateAuthorRequestDto): Promise<AuthorDto> {
        let url_ = this.baseUrl + "/api/library/authors";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateAuthor(_response);
        });
    }

    protected processCreateAuthor(response: Response): Promise<AuthorDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AuthorDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AuthorDto>(null as any);
    }

    deleteAuthor(authorId: string): Promise<AuthorDto> {
        let url_ = this.baseUrl + "/api/library/authors/{authorId}";
        if (authorId === undefined || authorId === null)
            throw new globalThis.Error("The parameter 'authorId' must be defined.");
        url_ = url_.replace("{authorId}", encodeURIComponent("" + authorId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteAuthor(_response);
        });
    }

    protected processDeleteAuthor(response: Response): Promise<AuthorDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AuthorDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AuthorDto>(null as any);
    }

    getBooks(): Promise<BookDto[]> {
        let url_ = this.baseUrl + "/api/library/books";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetBooks(_response);
        });
    }

    protected processGetBooks(response: Response): Promise<BookDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(BookDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BookDto[]>(null as any);
    }

    createBook(dto: CreateBookRequestDto): Promise<BookDto> {
        let url_ = this.baseUrl + "/api/library/books";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateBook(_response);
        });
    }

    protected processCreateBook(response: Response): Promise<BookDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = BookDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BookDto>(null as any);
    }

    updateBook(dto: UpdateBookRequestDto): Promise<BookDto> {
        let url_ = this.baseUrl + "/api/library/books";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateBook(_response);
        });
    }

    protected processUpdateBook(response: Response): Promise<BookDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = BookDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BookDto>(null as any);
    }

    deleteBook(bookId: string): Promise<BookDto> {
        let url_ = this.baseUrl + "/api/library/books/{bookId}";
        if (bookId === undefined || bookId === null)
            throw new globalThis.Error("The parameter 'bookId' must be defined.");
        url_ = url_.replace("{bookId}", encodeURIComponent("" + bookId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteBook(_response);
        });
    }

    protected processDeleteBook(response: Response): Promise<BookDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = BookDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BookDto>(null as any);
    }

    getGenres(): Promise<GenreDto[]> {
        let url_ = this.baseUrl + "/api/library/genres";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetGenres(_response);
        });
    }

    protected processGetGenres(response: Response): Promise<GenreDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GenreDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GenreDto[]>(null as any);
    }

    createGenre(dto: CreateGenreDto): Promise<GenreDto> {
        let url_ = this.baseUrl + "/api/library/genres";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateGenre(_response);
        });
    }

    protected processCreateGenre(response: Response): Promise<GenreDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GenreDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GenreDto>(null as any);
    }

    updateGenre(dto: UpdateGenreRequestDto): Promise<GenreDto> {
        let url_ = this.baseUrl + "/api/library/genres";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateGenre(_response);
        });
    }

    protected processUpdateGenre(response: Response): Promise<GenreDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GenreDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GenreDto>(null as any);
    }

    deleteGenre(genreId: string): Promise<GenreDto> {
        let url_ = this.baseUrl + "/api/library/genres/{genreId}";
        if (genreId === undefined || genreId === null)
            throw new globalThis.Error("The parameter 'genreId' must be defined.");
        url_ = url_.replace("{genreId}", encodeURIComponent("" + genreId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteGenre(_response);
        });
    }

    protected processDeleteGenre(response: Response): Promise<GenreDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GenreDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GenreDto>(null as any);
    }

    getBooksPaginated(page: number | undefined, pageSize: number | undefined): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/library/books/paginated?";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetBooksPaginated(_response);
        });
    }

    protected processGetBooksPaginated(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }

    fetchBooks(dto: FetchBooksRequestDto): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/library/books/fetch";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFetchBooks(_response);
        });
    }

    protected processFetchBooks(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }
}

export class AuthorDto implements IAuthorDto {
    id?: string;
    name?: string;
    createdAt?: Date | undefined;
    booksIds?: string[];

    constructor(data?: IAuthorDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            if (Array.isArray(_data["booksIds"])) {
                this.booksIds = [] as any;
                for (let item of _data["booksIds"])
                    this.booksIds!.push(item);
            }
        }
    }

    static fromJS(data: any): AuthorDto {
        data = typeof data === 'object' ? data : {};
        let result = new AuthorDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        if (Array.isArray(this.booksIds)) {
            data["booksIds"] = [];
            for (let item of this.booksIds)
                data["booksIds"].push(item);
        }
        return data;
    }
}

export interface IAuthorDto {
    id?: string;
    name?: string;
    createdAt?: Date | undefined;
    booksIds?: string[];
}

export class CreateAuthorRequestDto implements ICreateAuthorRequestDto {
    name!: string;

    constructor(data?: ICreateAuthorRequestDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): CreateAuthorRequestDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateAuthorRequestDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        return data;
    }
}

export interface ICreateAuthorRequestDto {
    name: string;
}

export class BookDto implements IBookDto {
    id?: string;
    title?: string;
    pages?: number;
    createdat?: Date | undefined;
    genre?: GenreDto | undefined;
    authorsIds?: string[];
    authors?: AuthorDto[];

    constructor(data?: IBookDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.pages = _data["pages"];
            this.createdat = _data["createdat"] ? new Date(_data["createdat"].toString()) : undefined as any;
            this.genre = _data["genre"] ? GenreDto.fromJS(_data["genre"]) : undefined as any;
            if (Array.isArray(_data["authorsIds"])) {
                this.authorsIds = [] as any;
                for (let item of _data["authorsIds"])
                    this.authorsIds!.push(item);
            }
            if (Array.isArray(_data["authors"])) {
                this.authors = [] as any;
                for (let item of _data["authors"])
                    this.authors!.push(AuthorDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): BookDto {
        data = typeof data === 'object' ? data : {};
        let result = new BookDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["pages"] = this.pages;
        data["createdat"] = this.createdat ? this.createdat.toISOString() : undefined as any;
        data["genre"] = this.genre ? this.genre.toJSON() : undefined as any;
        if (Array.isArray(this.authorsIds)) {
            data["authorsIds"] = [];
            for (let item of this.authorsIds)
                data["authorsIds"].push(item);
        }
        if (Array.isArray(this.authors)) {
            data["authors"] = [];
            for (let item of this.authors)
                data["authors"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IBookDto {
    id?: string;
    title?: string;
    pages?: number;
    createdat?: Date | undefined;
    genre?: GenreDto | undefined;
    authorsIds?: string[];
    authors?: AuthorDto[];
}

export class GenreDto implements IGenreDto {
    id?: string;
    name?: string;
    createdAt?: Date | undefined;
    books?: string[];

    constructor(data?: IGenreDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            if (Array.isArray(_data["books"])) {
                this.books = [] as any;
                for (let item of _data["books"])
                    this.books!.push(item);
            }
        }
    }

    static fromJS(data: any): GenreDto {
        data = typeof data === 'object' ? data : {};
        let result = new GenreDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        if (Array.isArray(this.books)) {
            data["books"] = [];
            for (let item of this.books)
                data["books"].push(item);
        }
        return data;
    }
}

export interface IGenreDto {
    id?: string;
    name?: string;
    createdAt?: Date | undefined;
    books?: string[];
}

export class CreateBookRequestDto implements ICreateBookRequestDto {
    title!: string;
    pages!: number;
    authorsIds?: string[];
    genreId?: string | undefined;

    constructor(data?: ICreateBookRequestDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            this.pages = _data["pages"];
            if (Array.isArray(_data["authorsIds"])) {
                this.authorsIds = [] as any;
                for (let item of _data["authorsIds"])
                    this.authorsIds!.push(item);
            }
            this.genreId = _data["genreId"];
        }
    }

    static fromJS(data: any): CreateBookRequestDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateBookRequestDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["pages"] = this.pages;
        if (Array.isArray(this.authorsIds)) {
            data["authorsIds"] = [];
            for (let item of this.authorsIds)
                data["authorsIds"].push(item);
        }
        data["genreId"] = this.genreId;
        return data;
    }
}

export interface ICreateBookRequestDto {
    title: string;
    pages: number;
    authorsIds?: string[];
    genreId?: string | undefined;
}

export class UpdateBookRequestDto implements IUpdateBookRequestDto {
    bookIdForLookupReference!: string;
    newTitle!: string;
    newPageCount!: number;
    authorsIds!: string[];
    genreId?: string | undefined;

    constructor(data?: IUpdateBookRequestDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.authorsIds = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.bookIdForLookupReference = _data["bookIdForLookupReference"];
            this.newTitle = _data["newTitle"];
            this.newPageCount = _data["newPageCount"];
            if (Array.isArray(_data["authorsIds"])) {
                this.authorsIds = [] as any;
                for (let item of _data["authorsIds"])
                    this.authorsIds!.push(item);
            }
            this.genreId = _data["genreId"];
        }
    }

    static fromJS(data: any): UpdateBookRequestDto {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateBookRequestDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["bookIdForLookupReference"] = this.bookIdForLookupReference;
        data["newTitle"] = this.newTitle;
        data["newPageCount"] = this.newPageCount;
        if (Array.isArray(this.authorsIds)) {
            data["authorsIds"] = [];
            for (let item of this.authorsIds)
                data["authorsIds"].push(item);
        }
        data["genreId"] = this.genreId;
        return data;
    }
}

export interface IUpdateBookRequestDto {
    bookIdForLookupReference: string;
    newTitle: string;
    newPageCount: number;
    authorsIds: string[];
    genreId?: string | undefined;
}

export class CreateGenreDto implements ICreateGenreDto {
    name!: string;

    constructor(data?: ICreateGenreDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): CreateGenreDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateGenreDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        return data;
    }
}

export interface ICreateGenreDto {
    name: string;
}

export class UpdateGenreRequestDto implements IUpdateGenreRequestDto {
    idToLookupBy!: string;
    newName!: string;

    constructor(data?: IUpdateGenreRequestDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.idToLookupBy = _data["idToLookupBy"];
            this.newName = _data["newName"];
        }
    }

    static fromJS(data: any): UpdateGenreRequestDto {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateGenreRequestDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["idToLookupBy"] = this.idToLookupBy;
        data["newName"] = this.newName;
        return data;
    }
}

export interface IUpdateGenreRequestDto {
    idToLookupBy: string;
    newName: string;
}

export class FetchBooksRequestDto implements IFetchBooksRequestDto {
    skip?: number;
    take?: number;
    orderBy?: BookOrdering;

    constructor(data?: IFetchBooksRequestDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.skip = _data["skip"];
            this.take = _data["take"];
            this.orderBy = _data["orderBy"];
        }
    }

    static fromJS(data: any): FetchBooksRequestDto {
        data = typeof data === 'object' ? data : {};
        let result = new FetchBooksRequestDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["skip"] = this.skip;
        data["take"] = this.take;
        data["orderBy"] = this.orderBy;
        return data;
    }
}

export interface IFetchBooksRequestDto {
    skip?: number;
    take?: number;
    orderBy?: BookOrdering;
}

export enum BookOrdering {
    NameAsc = 0,
    NameDesc = 1,
    LongestTitle = 2,
    MostPages = 3,
    GenreName = 4,
    MostRecentlyCreated = 5,
    MostProductiveAuthor = 6,
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}